version: "3"
services:
    api:
        container_name: ${ORG_NAME}-api
        image: coffee-supply-chain-hlf:latest
        env_file:
            - ../${ORG_ENV_FILE}
        working_dir: /usr/app
        command: npm run start
        volumes:
            - "../certs:/usr/app/certs"
            - "../wallet:/usr/app/wallet"
            - "../keyStore:/usr/app/keyStore"
            - "../network-config:/usr/app/network-config"
        ports:
            - ${API_PORT}:3000
        extra_hosts:
            - orderer0.orderer:${HLF_NW_IP} 
            - ca1.${ORG_NAME}:${HLF_NW_IP}
            - peer0.farmer:${HLF_NW_IP}
            - peer0.processor:${HLF_NW_IP}   
            - peer0.roaster:${HLF_NW_IP}
            - peer0.supplier:${HLF_NW_IP}
            - peer0.retailer:${HLF_NW_IP}
        networks:
            - app-network

networks:
  app-network:
    name: ${ORG_NAME}_app-network
    external: true
